# Generated by Django 3.1.3 on 2020-11-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_doc', models.TextField(max_length=15)),
                ('tipo_num_doc', models.TextField(max_length=1)),
                ('grupo_riesgo', models.TextField(max_length=3)),
                ('capacidad_pago', models.FloatField()),
            ],
        ),
    ]
